AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys Grafana into an existing kubernetes cluster (QSID)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing EKS cluster"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Grafana for EKS configuration
        Parameters:
          - KubeClusterName
          - Namespace
    ParameterLabels:
      KubeClusterName:
        default: EKS cluster name
      Namespace:
        default: Namespace
Parameters:
  KubeClusterName:
    Type: String
    Description: Name of the EKS cluster to deploy Grafana into.
  Namespace:
    Type: String
    Default: grafana
    Description: '[Optional] Kubernetes namespace to deploy Grafana into.'
Resources:
  GrafanaNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Manifest: |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: !Ref Namespace
  GrafanaHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref KubeClusterName
      Namespace: !GetAtt GrafanaNamespace.Name
      Chart: repo/chart
      Name: grafana
Outputs:
  GrafanaReleaseName:
    Value: !GetAtt GrafanaHelmChart.Name

