AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the Grafana Helm chart into an existing Kubernetes cluster (qs-1qde65hno)"
Metadata:
  LintSpellExclude:
    - Kubernetes
    - namespace
    - Namespace
    - grafana
  QuickStartDocumentation:
    EntrypointName: Launch into an existing Amazon EKS cluster
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Grafana for Amazon EKS configuration
        Parameters:
          - KubeClusterName
          - Namespace
          - GrafanaURL
          - OverrideValues
    ParameterLabels:
      KubeClusterName:
        default: Amazon EKS cluster name
      OverrideValues:
        default: Override values
      Namespace:
        default: Namespace
      GrafanaURL:
        default: Grafana URL
Parameters:
  KubeClusterName:
    Type: String
    Description: Name of the Amazon EKS cluster to deploy Grafana into.
  OverrideValues:
    Type: String
    Description: (Optional) URI to a file containing custom values to pass to the Helm install. Can be `http(s)://` or `s3://`.
    Default: ''
  Namespace:
    Type: String
    Default: grafana
    Description: (Optional) Kubernetes namespace to deploy Grafana into.
  GrafanaURL:
    Type: String
    Default: http://grafana-server.grafana.svc.cluster.local
    Description: (Optional) URL for Grafana. Defaults to the in-cluster Grafana deployed into the Grafana namespace.
Conditions:
  SupplyOverrides: !Not [!Equals [!Ref OverrideValues, '']]
Resources:
  GrafanaNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: 'kube-system'
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${Namespace}
  GrafanaHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: GrafanaNamespace
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref KubeClusterName
      Namespace: !Ref Namespace
      Chart: stable/grafana
      Name: grafana
      ValueOverrideURL: !If [SupplyOverrides, !Ref OverrideValues, !Ref 'AWS::NoValue']
      ValueYaml: !Sub |
        persistence:
          type: pvc
          enabled: true
          storageClassName: gp2
        service:
          type: LoadBalancer
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Grafana
              type: grafana
              url: ${GrafanaURL}
              access: proxy
              isDefault: true
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            node-exporter:
              gnetId: 1860
              revision: 21
              datasource: Grafana
            cluster:
              gnetId: 8685
              revision: 1
              datasource: Grafana
Outputs:
  GrafanaReleaseName:
    Value: !GetAtt GrafanaHelmChart.Name
